version: '1.0'
name: "fcecom-bridge-api-emporix"
services:
  node:
    build:
      context: .
    image: fcecom-bridge-api-emporix:${NODE_ENV}
    environment:
      - PORT=8080
      - LOG_LEVEL=${LOG_LEVEL}
      - NODE_ENV=${NODE_ENV}
      - BRIDGE_AUTH_USERNAME=admin
      - BRIDGE_AUTH_PASSWORD=nimda
      - CONN_MODE=HTTP
      - OAUTH_TOKEN_URL=https://api.emporix.io/oauth/token
      - BASE_URL=https://api.emporix.io
      - EMPORIX_TENANT=${EMPORIX_TENANT}
      - EMPORIX_CLIENT_ID=${EMPORIX_CLIENT_ID}
      - EMPORIX_CLIENT_SECRET=${EMPORIX_CLIENT_SECRET}
    ports:
      - "8080:8080"